apiVersion: v2
name: odin-eiger
description: IOC and Odin deployment for Eiger

type: application
version: 0.3.0
home: https://github.com/diamondlightsource/odin-helm-charts
sources:
  - https://github.com/DiamondLightSource/odin-helm-charts/tree/main/Charts/eiger

dependencies:
  - name: ioc-instance
    version: 5.0.0
    repository: "oci://ghcr.io/epics-containers/charts"
    import-values:
      - child: ioc-instance
        parent: ioc-instance
